import { useState } from 'react';
import { useTranslation } from 'react-i18next';
import Icon from '../../../shared/components/Icon';
import { useClipboard } from '../../../shared/hooks/useClipboard';
import useFeatureFlags from '../../../shared/hooks/useFeatureFlags';
import { htmlToMarkdown } from '../../../utils/markdownUtils';
import { getLocalizedContent } from '../../../utils/localizeContent';
import { deriveDocumentTitle, exportMarkdownDocument } from '../../../shared/utils/markdownExports';

/**
 * Copy and download actions for the canvas document.
 *
 * Downloads are generated by the server (`POST /api/exports`) with
 * `source: 'canvas'`: the document was edited in the browser, so the server
 * labels it "AI-assisted, edited by the user" (EU AI Act Art. 50, concept
 * §8.3). The editor holds HTML; it is converted to markdown for the request.
 *
 * @param {Object} props
 * @param {Object} props.app - App config (export feature flag, id, name)
 * @param {string} props.content - Editor content (HTML)
 * @param {Function} props.onClose - Closes the menu
 * @returns {JSX.Element|null}
 */
export default function ExportMenu({ app, content, onClose }) {
  const { t, i18n } = useTranslation();
  const { copyText, copyMarkdown, copyHTML } = useClipboard();
  const featureFlags = useFeatureFlags();
  const [busyFormat, setBusyFormat] = useState(null);
  const [error, setError] = useState(null);

  // Check if export is enabled at both platform and app levels
  const exportEnabled = featureFlags.isBothEnabled(app, 'export', true);

  const handleCopyText = async () => {
    await copyText(content);
    onClose();
  };

  const handleCopyMarkdown = async () => {
    await copyMarkdown(content);
    onClose();
  };

  const handleCopyHTML = async () => {
    await copyHTML(content);
    onClose();
  };

  const handleDownload = async format => {
    setBusyFormat(format);
    setError(null);
    try {
      const markdown = htmlToMarkdown(content || '');
      const appName = app?.name ? getLocalizedContent(app.name, i18n.language) : '';
      await exportMarkdownDocument({
        content: markdown,
        format,
        source: 'canvas',
        appId: app?.id,
        title: deriveDocumentTitle(
          markdown,
          appName || t('pages.appChat.export.document.untitled', 'Document')
        )
      });
      onClose();
    } catch (err) {
      console.error(`Canvas export to ${format} failed:`, err);
      setError(
        t('pages.appChat.export.errors.failed', {
          message: err?.message || '',
          defaultValue: 'The export failed: {{message}}'
        })
      );
    } finally {
      setBusyFormat(null);
    }
  };

  // If export is disabled, don't render anything
  if (!exportEnabled) {
    return null;
  }

  const downloadOptions = [
    {
      format: 'pdf',
      icon: 'file-text',
      label: t('pages.appChat.export.menu.asPdf', 'as PDF')
    },
    {
      format: 'docx',
      icon: 'document-text',
      label: t('pages.appChat.export.menu.asDocx', 'as Word document')
    },
    {
      format: 'html',
      icon: 'code',
      label: t('canvas.export.downloadHTML', 'as HTML')
    },
    {
      format: 'markdown',
      icon: 'code',
      label: t('canvas.export.downloadMarkdown', 'as Markdown')
    }
  ];

  const itemClass =
    'w-full text-left px-3 py-2 text-sm text-gray-700 dark:text-gray-200 hover:bg-gray-100 dark:hover:bg-gray-700 rounded-sm flex items-center gap-2 transition-colors whitespace-nowrap disabled:opacity-50 disabled:cursor-not-allowed';

  return (
    <div
      className="absolute top-full right-0 mt-2 bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-lg shadow-lg z-50 min-w-56"
      aria-busy={busyFormat !== null}
    >
      <div className="p-2">
        <div className="px-2 py-1 text-xs font-semibold text-gray-500 dark:text-gray-400 uppercase tracking-wide">
          {t('canvas.export.copyOptions', 'Copy Options')}
        </div>
        <button type="button" onClick={handleCopyText} className={itemClass}>
          <Icon name="document-text" size="sm" />
          {t('canvas.export.copyText', 'as Text')}
        </button>
        <button type="button" onClick={handleCopyMarkdown} className={itemClass}>
          <Icon name="code" size="sm" />
          {t('canvas.export.copyMarkdown', 'as Markdown')}
        </button>
        <button type="button" onClick={handleCopyHTML} className={itemClass}>
          <Icon name="code" size="sm" />
          {t('canvas.export.copyHTML', 'as HTML')}
        </button>

        <hr className="my-2 border-gray-200 dark:border-gray-700" />

        <div className="px-2 py-1 text-xs font-semibold text-gray-500 dark:text-gray-400 uppercase tracking-wide">
          {t('canvas.export.downloadOptions', 'Download Options')}
        </div>
        {downloadOptions.map(option => (
          <button
            key={option.format}
            type="button"
            onClick={() => handleDownload(option.format)}
            disabled={busyFormat !== null}
            className={itemClass}
          >
            {busyFormat === option.format ? (
              <span
                className="inline-block h-4 w-4 animate-spin rounded-full border-2 border-gray-400 border-t-transparent"
                aria-hidden="true"
              />
            ) : (
              <Icon name={option.icon} size="sm" />
            )}
            {option.label}
          </button>
        ))}
        <p role="status" aria-live="polite" className="sr-only">
          {busyFormat ? t('pages.appChat.export.status.preparing', 'Preparing the export…') : ''}
        </p>
        {error && (
          <p role="alert" className="px-3 py-2 text-xs text-red-700 dark:text-red-300 max-w-64">
            {error}
          </p>
        )}
      </div>
    </div>
  );
}
