[book]
title = "iHub Apps Documentation"
authors = ["IntraFind"]
description = "iHub Applications Platform - AI-powered applications with LLM integration"
src = "docs"

[build]
create-missing = false

[output.html]
theme = "theme"
additional-css = ["theme/custom.css"]
git-repository-url = "https://github.com/intrafind/ai-hub-apps"
edit-url-template = "https://github.com/intrafind/ai-hub-apps/edit/main/docs/{path}"

[preprocessor.template]
command = "mdbook-template"
