import globals from 'globals';
import eslintReact from '@eslint-react/eslint-plugin';

export default [
  {
    ignores: [
      'node_modules/**',
      'dist/**',
      'dist-bin/**',
      'build/**',
      'coverage/**',
      '*.min.js',
      'client/node_modules/**',
      'server/node_modules/**',
      'client/dist/**',
      // Generated by `npm run extension:build` — copies of client/dist/{extension,assets}
      // for unpacked Chrome loading. Source lives under client/extension/ + client/src/.
      'browser-extension/extension/**',
      'browser-extension/assets/**',
      'docs/**',
      'examples/**',
      'concepts/**',
      'logs/**',
      '*.log',
      '.github/**',
      '.claude/**',
      '.worktrees/**'
    ]
  },
  {
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      globals: {
        ...globals.node,
        ...globals.browser,
        ...globals.es2024
      }
    },
    rules: {
      'no-unused-vars': [
        'warn',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_'
        }
      ],
      'no-console': 'off'
      // Removed all formatting rules that conflict with Prettier
      // Prettier handles: indent, quotes, semi, no-multiple-empty-lines, eol-last,
      // comma-dangle, object-curly-spacing, array-bracket-spacing, space-before-function-paren,
      // keyword-spacing, space-infix-ops, no-trailing-spaces
    }
  },
  {
    files: ['client/**/*.jsx', 'client/**/*.js'],
    ...eslintReact.configs.recommended,
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      parserOptions: {
        ecmaFeatures: {
          jsx: true
        }
      },
      globals: {
        ...globals.browser,
        ...globals.es2024
      }
    },
    rules: {
      ...eslintReact.configs.recommended.rules,
      // Disable RSC rules — not a React Server Components project
      '@eslint-react/rsc/function-definition': 'off'
    }
  },
  {
    files: ['server/**/*.js'],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      globals: {
        ...globals.node,
        ...globals.es2024
      }
    }
  }
];
