import globals from 'globals';
import eslintReact from '@eslint-react/eslint-plugin';
import jsxA11y from 'eslint-plugin-jsx-a11y';

export default [
  {
    ignores: [
      'node_modules/**',
      'dist/**',
      'dist-bin/**',
      'build/**',
      'coverage/**',
      '*.min.js',
      'client/node_modules/**',
      'server/node_modules/**',
      'client/dist/**',
      // Generated by `npm run extension:build` — copies of client/dist/{extension,assets}
      // for unpacked Chrome loading. Source lives under client/extension/ + client/src/.
      'browser-extension/extension/**',
      'browser-extension/assets/**',
      'docs/**',
      'examples/**',
      'concepts/**',
      'logs/**',
      '*.log',
      '.github/**',
      '.claude/**',
      '.worktrees/**'
    ]
  },
  {
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      globals: {
        ...globals.node,
        ...globals.browser,
        ...globals.es2024
      }
    },
    rules: {
      'no-unused-vars': [
        'warn',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_'
        }
      ],
      'no-console': 'off'
      // Removed all formatting rules that conflict with Prettier
      // Prettier handles: indent, quotes, semi, no-multiple-empty-lines, eol-last,
      // comma-dangle, object-curly-spacing, array-bracket-spacing, space-before-function-paren,
      // keyword-spacing, space-infix-ops, no-trailing-spaces
    }
  },
  {
    files: ['client/**/*.jsx', 'client/**/*.js'],
    ...eslintReact.configs.recommended,
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      parserOptions: {
        ecmaFeatures: {
          jsx: true
        }
      },
      globals: {
        ...globals.browser,
        ...globals.es2024
      }
    },
    plugins: {
      ...eslintReact.configs.recommended.plugins,
      'jsx-a11y': jsxA11y
    },
    rules: {
      ...eslintReact.configs.recommended.rules,
      // Disable RSC rules — not a React Server Components project
      '@eslint-react/rsc/function-definition': 'off',
      // WCAG 2.2 AA static analysis via eslint-plugin-jsx-a11y.
      // Start from the plugin's recommended ruleset but downgrade `error` to
      // `warn` so a11y findings don't block ongoing development. Rules the
      // preset disables (e.g. the deprecated `label-has-for`) stay disabled,
      // and per-rule option objects are preserved. Rules are promoted back to
      // `error` as violations are remediated. See docs/accessibility.md.
      ...Object.fromEntries(
        Object.entries(jsxA11y.flatConfigs.recommended.rules).map(([rule, setting]) => {
          // Array form: ['error', { ...options }] — keep options, lower severity.
          if (Array.isArray(setting)) {
            const [severity, ...options] = setting;
            return [rule, severity === 'off' ? setting : ['warn', ...options]];
          }
          // String form: 'error' | 'warn' | 'off'.
          return [rule, setting === 'off' ? 'off' : 'warn'];
        })
      ),
      // client/src/api/endpoints/admin.js was deleted (#1743) in favor of
      // client/src/api/adminApi.js as the single admin API client layer.
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: ['**/api/endpoints/admin', '**/api/endpoints/admin.js'],
              message:
                "Import from 'api/adminApi' instead — 'api/endpoints/admin' was removed in #1743."
            }
          ]
        }
      ]
    }
  },
  {
    files: ['server/**/*.js'],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      globals: {
        ...globals.node,
        ...globals.es2024
      }
    }
  }
];
