/**
 * SubWorkflowMaterializer
 *
 * Creates a valid workflow definition JSON from a planner-generated plan.
 * The resulting workflow follows the structure:
 *   start -> task1(agent) -> task2(agent) -> ... -> [synthesizer?] -> end
 *
 * Tasks are connected sequentially by default, but can specify explicit
 * dependencies via the `dependsOn` array. An optional synthesizer agent
 * node is appended before the end node when `parentConfig.synthesize` is true.
 *
 * @module services/workflow/SubWorkflowMaterializer
 */

import logger from '../../utils/logger.js';

function dedupeStrings(arr) {
  return Array.from(new Set((arr || []).filter(v => typeof v === 'string')));
}

export class SubWorkflowMaterializer {
  /**
   * Materialize a plan into a runnable workflow definition.
   *
   * @param {Object} plan - The plan generated by the planner LLM
   * @param {Array<Object>} plan.tasks - Array of task objects with id, title, description, tools, dependsOn
   * @param {string} [plan.reasoning] - Brief explanation of the plan strategy
   * @param {Object} parentConfig - Configuration from the parent planner node
   * @param {boolean} [parentConfig.synthesize] - Whether to add a synthesizer node before end
   * @param {Object} [parentConfig.taskTemplate] - Default config template applied to every task node
   * @param {number} depth - Current sub-workflow nesting depth (for logging)
   * @returns {Object} A complete workflow definition ready for WorkflowEngine.start()
   */
  static materialize(plan, parentConfig, depth) {
    const nodes = [];
    const edges = [];

    // Start node
    nodes.push({
      id: 'sub-start',
      type: 'start',
      name: { en: 'Sub-workflow Start' },
      position: { x: 0, y: 0 },
      config: {}
    });

    // Create agent nodes for each task in the plan.
    // CRITICAL: Destructure tools/apps/sources from taskTemplate before
    // spreading — each is additive at the task level (the planner may
    // spotlight a per-task subset on top of the profile-wide template), so
    // the spread of restTemplate must NOT overwrite the merged arrays we
    // build below.
    const {
      tools: templateTools,
      apps: templateApps,
      sources: templateSources,
      ...restTemplate
    } = parentConfig.taskTemplate || {};

    const taskNodes = plan.tasks.map((task, index) => {
      // The agent's persona system prompt lives on the profile (carried via
      // restTemplate.system). Earlier versions of this materializer
      // overrode that with task.description, which erased the agent's
      // instructions on every task. Now we keep the profile system and put
      // the task instruction in the user prompt.
      const taskInstruction = task.title
        ? `${task.title}\n\n${task.description || ''}`.trim()
        : task.description || `Execute task ${task.id || index}.`;

      // Build the user prompt with two context blocks so each task sees
      // (a) the brief and inbox item the runtime loaded before the planner,
      // and (b) what previous tasks produced (rendered from
      // `state.data._taskResults`, populated by PromptNodeExecutor's runtime
      // auto-persist after each planner task completes).
      //
      // `{{previousTaskResults}}` is a special template variable the prompt
      // executor formats on-the-fly from the accumulated task results map.
      // It renders empty on the first task and gracefully accumulates as
      // later tasks complete — no more reliance on fragile `{{nodeResults}}`.
      const promptParts = [];
      if (index === 0) {
        promptParts.push(
          '## Context\n\n' +
            '- Original brief: {{brief}}\n' +
            '- Current inbox item (if any): {{currentInboxItem}}'
        );
      } else {
        // Earlier tasks have already produced findings. Make it explicit
        // that this task BUILDS on top of them — extending, deepening, or
        // analyzing the prior output rather than restarting the research
        // from scratch. Without this nudge, an LLM may treat each task as
        // independent and produce parallel/overlapping work.
        promptParts.push(
          '## Context\n\n' +
            '- Original brief: {{brief}}\n' +
            '- Current inbox item (if any): {{currentInboxItem}}\n\n' +
            '## Previous task results — BUILD ON THESE\n\n' +
            'The tasks below this one have already run. Their findings are ' +
            'the foundation you extend in this step. DO NOT repeat work ' +
            'they already did. DO NOT contradict facts they established ' +
            'unless you have a verified source that overrides theirs. Your ' +
            'job is to add NEW analysis, deeper detail, or fresh evidence ' +
            'that complements what is here:\n\n' +
            '{{previousTaskResults}}'
        );
      }
      promptParts.push(`## Current task\n\n${taskInstruction}`);

      // Grounding discipline — the report generator at the end of the run
      // can only cite what the task workers captured. Every task that has
      // search/extract tools available should USE them, record source URLs
      // per fact, and avoid fabricating. The runtime separately captures
      // tool-call URLs into `state.data._citations` so the synthesizer has
      // a ledger to cite from, but the task worker's own output should
      // also include source URLs inline so the synthesizer can connect
      // facts to citations cleanly.
      // Planner-driven per-task tool selection (Gemini grounding workaround):
      // when the planner emits a populated `tools` array on a task, treat that
      // as authoritative — DO NOT merge with templateTools. The planner is
      // schema-bound to choose from templateTools, so its choice is always a
      // subset. Merging would re-add every templateTool and undo the planner's
      // attempt to split webSearch off from function tools.
      //   - task.tools undefined / missing → inherit templateTools (legacy)
      //   - task.tools === []              → no tools for this task
      //   - task.tools === [...non-empty]  → use exactly these
      const taskToolsExplicit = Array.isArray(task.tools);
      const taskAppsExplicit = Array.isArray(task.apps);
      const taskSourcesExplicit = Array.isArray(task.sources);
      const effectiveTools = taskToolsExplicit
        ? dedupeStrings(task.tools)
        : Array.isArray(templateTools)
          ? dedupeStrings(templateTools)
          : [];
      const effectiveApps = taskAppsExplicit
        ? dedupeStrings(task.apps)
        : Array.isArray(templateApps)
          ? dedupeStrings(templateApps)
          : [];
      const effectiveSources = taskSourcesExplicit
        ? dedupeStrings(task.sources)
        : Array.isArray(templateSources)
          ? dedupeStrings(templateSources)
          : [];

      const hasSearchLikeTool = effectiveTools.some(t => {
        if (typeof t !== 'string') return false;
        const id = t.toLowerCase();
        return id === 'websearch' || id === 'webcontentextractor' || id.startsWith('source_');
      });
      if (hasSearchLikeTool) {
        promptParts.push(
          '## Grounding rules — MULTI-SOURCE REQUIRED\n\n' +
            'Quality bar: do not stop after the first hit. A research task is ' +
            'not complete until you have triangulated facts across multiple ' +
            'independent sources.\n\n' +
            '1. Run AT LEAST 3 distinct searches with different query angles ' +
            'before drafting your output. Vary phrasing, vary the angle. For ' +
            'a person: try `"<name> <known company>"`, `"<name> LinkedIn"`, ' +
            '`"<name> GitHub"`, `"<name> interview"`, `"<name> conference talk"`, ' +
            '`"<name> publication"`. For a company: `"<company> about"`, ' +
            '`"<company> founded"`, `"<company> press"`, `"<company> careers"`. ' +
            'For a topic: try the term, a synonym, and a related concept.\n' +
            '2. CROSS-REFERENCE every concrete claim against AT LEAST 2 ' +
            'independent sources. State which sources back each fact. When ' +
            'sources disagree, SURFACE THE DISAGREEMENT explicitly — do not ' +
            'silently pick one.\n' +
            '3. If the first search returns generic / SEO-spam / wikipedia-only ' +
            'results, that is a SIGNAL TO SEARCH MORE — try narrower, more ' +
            "specific queries. Don't accept thin evidence.\n" +
            '4. For every claim in your output, include the source URL inline ' +
            'in parentheses, e.g. `"Founded 2015 (https://example.com/about)"`. ' +
            'If a fact is grounded in multiple sources, list all of them.\n' +
            '5. End with a "## Sources" section listing every URL you actually ' +
            'consulted, ordered by relevance. Note next to each which facts it ' +
            'backs.\n' +
            '6. DO NOT invent facts. Do NOT extrapolate. If something cannot ' +
            'be verified after 3+ searches, say so explicitly: ' +
            '`"[unverified — no source found despite searches X, Y, Z]"`.\n' +
            '7. If your current task title implies depth ("research", ' +
            '"analyze", "find out"), aim for 5+ sources rather than 3. Trust ' +
            'is built by thoroughness.'
        );
      }

      const taskId = task.id || `task-${index}`;
      const taskTitle = task.title || `Task ${index + 1}`;

      return {
        id: taskId,
        type: 'prompt',
        name: { en: taskTitle },
        position: { x: 0, y: (index + 1) * 100 },
        config: {
          ...restTemplate,
          // Marker the agent tool registrar uses to strip lifecycle tools
          // (inbox/artifact/mark-done) from materialized tasks — the runtime
          // owns inbox lifecycle and artifact persistence, not individual
          // plan tasks. The PromptNodeExecutor also reads `_isPlannerTask`
          // for its runtime auto-persist of per-task results.
          _isPlannerTask: true,
          _taskId: taskId,
          _taskTitle: taskTitle,
          // Bedrock (and other strict APIs) require at least one user message.
          prompt: promptParts.join('\n\n'),
          // Per-task tools / apps / sources — planner-authoritative when the
          // planner emitted the field, falling back to the profile-wide
          // template otherwise. See `taskToolsExplicit` block above for the
          // full semantics. The planner's response schema enum-binds each
          // field (tools/apps/sources) to its catalog when the catalog is
          // non-empty, so unknown ids are rejected at structured-output
          // time. Backward-compat for hand-written plans that omit a field
          // is via the explicit-array check (omit → inherit template).
          tools: effectiveTools,
          apps: effectiveApps,
          sources: effectiveSources
          // No `outputVariable` — the runtime auto-persists planner-task
          // results to state.data._taskResults[<taskId>] via
          // PromptNodeExecutor._autoPersistResult. The legacy flat
          // `task_<id>_result` state key it used to produce duplicated
          // _taskResults[<id>].content and had zero readers.
        }
      };
    });

    // Assert every materialized prompt task has both a system message and a
    // user/prompt content. A node with only a system message would be
    // rejected by stricter providers (e.g. Bedrock: "conversation must start
    // with a user message"). Fail fast at materialize time with a helpful
    // diagnostic instead of failing 30 seconds later inside the provider
    // adapter with a opaque error.
    for (const tn of taskNodes) {
      const hasSystem =
        tn.config?.system &&
        (typeof tn.config.system === 'string'
          ? tn.config.system.trim().length > 0
          : Object.values(tn.config.system).some(
              v => typeof v === 'string' && v.trim().length > 0
            ));
      const hasPrompt = typeof tn.config?.prompt === 'string' && tn.config.prompt.trim().length > 0;
      if (!hasSystem || !hasPrompt) {
        const reason = !hasSystem ? 'missing system message' : 'missing user prompt content';
        throw new Error(
          `SubWorkflowMaterializer: task node ${tn.id} is malformed (${reason}). ` +
            `Each task must carry both a system message and a user prompt. ` +
            `Source plan task: ${JSON.stringify({
              id: plan.tasks[taskNodes.indexOf(tn)]?.id,
              title: plan.tasks[taskNodes.indexOf(tn)]?.title
            })}`
        );
      }
    }

    nodes.push(...taskNodes);

    // Optional synthesizer node before end
    if (parentConfig.synthesize && taskNodes.length > 0) {
      const synthId = 'synthesizer';
      nodes.push({
        id: synthId,
        type: 'prompt',
        name: { en: 'Synthesizer' },
        position: { x: 0, y: (taskNodes.length + 1) * 100 },
        config: {
          system:
            'Synthesize all task results into a coherent final output. ' +
            'Review and combine the outputs from all previous tasks.',
          outputVariable: 'synthesized_result'
        }
      });
    }

    // Optional dynamic-tasks drain tail. When the parent planner is configured
    // with `dynamicTasks.enabled`, agents executing the materialized tasks can
    // push more tasks onto `_taskQueue`; the drain loop processes them after
    // the planned tasks are done. This is the V1 Planner+drain mechanic.
    const dynamicTasksEnabled = !!parentConfig.dynamicTasks?.enabled;
    const dynamicTasksMaxDepth = parentConfig.dynamicTasks?.maxDepth ?? 3;
    let drainNodeId = null;
    if (dynamicTasksEnabled && taskNodes.length > 0) {
      drainNodeId = 'drain';
      const taskRunnerBody = {
        id: 'drain-task-runner',
        type: 'prompt',
        name: { en: 'Drain task runner' },
        position: { x: 0, y: (nodes.length + 1) * 100 },
        config: {
          ...restTemplate,
          system: parentConfig.taskTemplate?.system || {
            en: 'Process the current task in `_currentTask`.'
          },
          tools: templateTools || [],
          // Same as the planner-generated tasks above: drain workers should
          // not own inbox lifecycle. The orchestrator reads/marks the inbox.
          _isPlannerTask: true,
          dynamicTasks: { enabled: true, maxDepth: dynamicTasksMaxDepth }
        }
      };
      nodes.push({
        id: drainNodeId,
        type: 'loop',
        name: { en: 'Drain Dynamic Tasks' },
        position: { x: 0, y: (nodes.length + 1) * 100 },
        config: {
          mode: 'drain',
          queueKey: '_taskQueue',
          body: [taskRunnerBody],
          maxIterations: 50
        }
      });
    }

    // End node
    nodes.push({
      id: 'sub-end',
      type: 'end',
      name: { en: 'Sub-workflow End' },
      position: { x: 0, y: nodes.length * 100 },
      config: {}
    });

    // Build edges connecting the nodes
    if (taskNodes.length > 0) {
      // start -> first task
      edges.push({
        id: 'edge-start-t0',
        source: 'sub-start',
        target: taskNodes[0].id
      });

      // Chain tasks. Two rules combined:
      //   1. Sequential safety net — `tasks[i-1] → tasks[i]` for every i>0,
      //      regardless of `dependsOn`. This guarantees execution follows the
      //      planner's array order even when the LLM forgets to declare a
      //      dependency, so a task that needs prior output never runs first.
      //   2. Explicit `dependsOn` edges are added on top. They don't replace
      //      the sequential chain — they just add upstream wait points. This
      //      means a dependent task waits for BOTH its explicit dependencies
      //      AND its array-predecessor. Costs some potential parallelism but
      //      makes ordering predictable and bug-resistant.
      for (let i = 0; i < taskNodes.length; i++) {
        const task = plan.tasks[i];
        if (i > 0) {
          edges.push({
            id: `edge-t${i - 1}-t${i}`,
            source: taskNodes[i - 1].id,
            target: taskNodes[i].id
          });
        }
        if (Array.isArray(task.dependsOn) && task.dependsOn.length > 0) {
          for (const dep of task.dependsOn) {
            // Skip degenerate self-reference and the trivial array-predecessor
            // (already covered by the sequential edge above) to avoid creating
            // a duplicate edge.
            if (dep === taskNodes[i].id) continue;
            if (i > 0 && dep === taskNodes[i - 1].id) continue;
            edges.push({
              id: `edge-${dep}-${taskNodes[i].id}`,
              source: dep,
              target: taskNodes[i].id
            });
          }
        }
      }

      // Build the tail chain: lastTask → [synthesizer?] → [drain?] → sub-end.
      // Each step writes one edge; the final hop targets sub-end.
      const lastTask = taskNodes[taskNodes.length - 1];
      let prev = lastTask.id;
      if (parentConfig.synthesize) {
        edges.push({ id: `edge-${prev}-synth`, source: prev, target: 'synthesizer' });
        prev = 'synthesizer';
      }
      if (drainNodeId) {
        edges.push({ id: `edge-${prev}-drain`, source: prev, target: drainNodeId });
        prev = drainNodeId;
      }
      edges.push({ id: `edge-${prev}-end`, source: prev, target: 'sub-end' });
    } else {
      // No tasks - connect start directly to end
      edges.push({
        id: 'edge-start-end',
        source: 'sub-start',
        target: 'sub-end'
      });
    }

    logger.info({
      component: 'SubWorkflowMaterializer',
      message: 'Materialized sub-workflow from plan',
      taskCount: taskNodes.length,
      hasSynthesizer: !!parentConfig.synthesize,
      depth
    });

    return {
      id: `sub-workflow-${Date.now()}`,
      name: { en: 'Dynamic Sub-workflow' },
      description: { en: plan.reasoning || 'Auto-generated sub-workflow' },
      version: '1.0.0',
      enabled: true,
      config: {
        allowCycles: false,
        maxIterations: 50,
        maxNodes: 50
      },
      nodes,
      edges
    };
  }
}

export default SubWorkflowMaterializer;
