/**
 * SubWorkflowMaterializer
 *
 * Creates a valid workflow definition JSON from a planner-generated plan.
 * The resulting workflow follows the structure:
 *   start -> task1(agent) -> task2(agent) -> ... -> [synthesizer?] -> end
 *
 * Tasks are connected sequentially by default, but can specify explicit
 * dependencies via the `dependsOn` array. An optional synthesizer agent
 * node is appended before the end node when `parentConfig.synthesize` is true.
 *
 * @module services/workflow/SubWorkflowMaterializer
 */

import logger from '../../utils/logger.js';

export class SubWorkflowMaterializer {
  /**
   * Materialize a plan into a runnable workflow definition.
   *
   * @param {Object} plan - The plan generated by the planner LLM
   * @param {Array<Object>} plan.tasks - Array of task objects with id, title, description, tools, dependsOn
   * @param {string} [plan.reasoning] - Brief explanation of the plan strategy
   * @param {Object} parentConfig - Configuration from the parent planner node
   * @param {boolean} [parentConfig.synthesize] - Whether to add a synthesizer node before end
   * @param {Object} [parentConfig.taskTemplate] - Default config template applied to every task node
   * @param {number} depth - Current sub-workflow nesting depth (for logging)
   * @returns {Object} A complete workflow definition ready for WorkflowEngine.start()
   */
  static materialize(plan, parentConfig, depth) {
    const nodes = [];
    const edges = [];

    // Start node
    nodes.push({
      id: 'sub-start',
      type: 'start',
      name: { en: 'Sub-workflow Start' },
      position: { x: 0, y: 0 },
      config: {}
    });

    // Create agent nodes for each task in the plan.
    // CRITICAL: Destructure tools from taskTemplate before spreading to prevent overwrite.
    const { tools: templateTools, ...restTemplate } = parentConfig.taskTemplate || {};

    const taskNodes = plan.tasks.map((task, index) => ({
      id: task.id || `task-${index}`,
      type: 'prompt',
      name: { en: task.title || `Task ${index + 1}` },
      position: { x: 0, y: (index + 1) * 100 },
      config: {
        ...restTemplate,
        system: task.description,
        // Bedrock (and other strict APIs) require at least one user message.
        // The task's title/description gives the agent a concrete instruction
        // to act on; without this the node would send only a system message
        // and the provider would reject with "conversation must start with a
        // user message".
        prompt: task.title
          ? `${task.title}\n\n${task.description || ''}`.trim()
          : task.description || `Execute task ${task.id || index}.`,
        tools: [...(task.tools || []), ...(templateTools || [])],
        outputVariable: `task_${task.id || index}_result`
      }
    }));

    nodes.push(...taskNodes);

    // Optional synthesizer node before end
    if (parentConfig.synthesize && taskNodes.length > 0) {
      const synthId = 'synthesizer';
      nodes.push({
        id: synthId,
        type: 'prompt',
        name: { en: 'Synthesizer' },
        position: { x: 0, y: (taskNodes.length + 1) * 100 },
        config: {
          system:
            'Synthesize all task results into a coherent final output. ' +
            'Review and combine the outputs from all previous tasks.',
          outputVariable: 'synthesized_result'
        }
      });
    }

    // Optional dynamic-tasks drain tail. When the parent planner is configured
    // with `dynamicTasks.enabled`, agents executing the materialized tasks can
    // push more tasks onto `_taskQueue`; the drain loop processes them after
    // the planned tasks are done. This is the V1 Planner+drain mechanic.
    const dynamicTasksEnabled = !!parentConfig.dynamicTasks?.enabled;
    const dynamicTasksMaxDepth = parentConfig.dynamicTasks?.maxDepth ?? 3;
    let drainNodeId = null;
    if (dynamicTasksEnabled && taskNodes.length > 0) {
      drainNodeId = 'drain';
      const taskRunnerBody = {
        id: 'drain-task-runner',
        type: 'prompt',
        name: { en: 'Drain task runner' },
        position: { x: 0, y: (nodes.length + 1) * 100 },
        config: {
          ...restTemplate,
          system: parentConfig.taskTemplate?.system || {
            en: 'Process the current task in `_currentTask`.'
          },
          tools: templateTools || [],
          dynamicTasks: { enabled: true, maxDepth: dynamicTasksMaxDepth }
        }
      };
      nodes.push({
        id: drainNodeId,
        type: 'loop',
        name: { en: 'Drain Dynamic Tasks' },
        position: { x: 0, y: (nodes.length + 1) * 100 },
        config: {
          mode: 'drain',
          queueKey: '_taskQueue',
          body: [taskRunnerBody],
          maxIterations: 50
        }
      });
    }

    // End node
    nodes.push({
      id: 'sub-end',
      type: 'end',
      name: { en: 'Sub-workflow End' },
      position: { x: 0, y: nodes.length * 100 },
      config: {}
    });

    // Build edges connecting the nodes
    if (taskNodes.length > 0) {
      // start -> first task
      edges.push({
        id: 'edge-start-t0',
        source: 'sub-start',
        target: taskNodes[0].id
      });

      // Chain tasks based on dependsOn or sequential order
      for (let i = 0; i < taskNodes.length; i++) {
        const task = plan.tasks[i];
        if (task.dependsOn && task.dependsOn.length > 0) {
          for (const dep of task.dependsOn) {
            edges.push({
              id: `edge-${dep}-${taskNodes[i].id}`,
              source: dep,
              target: taskNodes[i].id
            });
          }
        } else if (i > 0) {
          edges.push({
            id: `edge-t${i - 1}-t${i}`,
            source: taskNodes[i - 1].id,
            target: taskNodes[i].id
          });
        }
      }

      // Build the tail chain: lastTask → [synthesizer?] → [drain?] → sub-end.
      // Each step writes one edge; the final hop targets sub-end.
      const lastTask = taskNodes[taskNodes.length - 1];
      let prev = lastTask.id;
      if (parentConfig.synthesize) {
        edges.push({ id: `edge-${prev}-synth`, source: prev, target: 'synthesizer' });
        prev = 'synthesizer';
      }
      if (drainNodeId) {
        edges.push({ id: `edge-${prev}-drain`, source: prev, target: drainNodeId });
        prev = drainNodeId;
      }
      edges.push({ id: `edge-${prev}-end`, source: prev, target: 'sub-end' });
    } else {
      // No tasks - connect start directly to end
      edges.push({
        id: 'edge-start-end',
        source: 'sub-start',
        target: 'sub-end'
      });
    }

    logger.info({
      component: 'SubWorkflowMaterializer',
      message: 'Materialized sub-workflow from plan',
      taskCount: taskNodes.length,
      hasSynthesizer: !!parentConfig.synthesize,
      depth
    });

    return {
      id: `sub-workflow-${Date.now()}`,
      name: { en: 'Dynamic Sub-workflow' },
      description: { en: plan.reasoning || 'Auto-generated sub-workflow' },
      version: '1.0.0',
      enabled: true,
      config: {
        allowCycles: false,
        maxIterations: 50,
        maxNodes: 50
      },
      nodes,
      edges
    };
  }
}

export default SubWorkflowMaterializer;
