import registerAdminAuthRoutes from './admin/auth.js';
import registerAdminLdapTestRoutes from './admin/ldapTest.js';
import registerAdminOAuthRoutes from './admin/oauthClients.js';
import registerAdminOAuthCimdRoutes from './admin/oauthCimdClients.js';
import registerAdminOAuthConnectionRoutes from './admin/oauthConnections.js';
import registerAdminCacheRoutes from './admin/cache.js';
import registerAdminConfigRoutes from './admin/configs.js';
import registerAdminAppsRoutes from './admin/apps.js';
import registerAdminModelsRoutes from './admin/models.js';
import registerAdminProvidersRoutes from './admin/providers.js';
import registerAdminPromptsRoutes from './admin/prompts.js';
import registerAdminSourcesRoutes from './admin/sources.js';
import registerAdminGroupRoutes from './admin/groups.js';
import registerAdminContentAccessRoutes from './admin/contentAccess.js';
import registerAdminTranslateRoute from './admin/translate.js';
import registerAdminPagesRoutes from './admin/pages.js';
import registerAdminUIRoutes from './admin/ui.js';
import registerBackupRoutes from './admin/backup.js';
import registerAdminSchemasRoutes from './admin/schemas.js';
import registerAdminVersionRoutes from './admin/version.js';
import registerAdminToolsRoutes from './admin/tools.js';
import registerAdminSkillsRoutes from './admin/skills.js';
import registerAdminMarketplaceRoutes from './admin/marketplace.js';
import registerAdminLoggingRoutes from './admin/logging.js';
import registerAdminSSLRoutes from './admin/ssl.js';
import registerAdminCorsRoutes from './admin/cors.js';
import registerAdminSsrfRoutes from './admin/ssrf.js';
import registerAdminProxyRoutes from './admin/proxy.js';
import registerAdminFeaturesRoutes from './admin/features.js';
import registerAdminUsageRoutes from './admin/usage.js';
import registerAdminUpdateRoutes from './admin/update.js';
import registerIntegrationTestRoutes from './admin/integrationTest.js';
import registerAdminOfficeIntegrationRoutes from './admin/officeIntegration.js';
import registerAdminBrowserExtensionRoutes from './admin/browserExtension.js';
import registerAdminNextcloudEmbedRoutes from './admin/nextcloudEmbed.js';
import registerAdminMcpServersRoutes from './admin/mcpServers.js';
import registerAdminCredentialsRoutes from './admin/credentials.js';
import registerAdminAgentsRoutes from './admin/agents.js';
import registerAdminAgentInboxesRoutes from './admin/agentInboxes.js';
import registerAdminSearchRoutes from './admin/search.js';
import registerAdminAuditLogRoutes from './admin/auditLog.js';
import registerAdminChangelogRoutes from './admin/changelog.js';
import registerAdminChangesRoutes from './admin/changes.js';
import registerAdminOverviewRoutes from './admin/overview.js';

export default async function registerAdminRoutes(app) {
  registerAdminAuthRoutes(app);
  registerAdminLdapTestRoutes(app);
  registerAdminOAuthRoutes(app);
  registerAdminOAuthCimdRoutes(app);
  registerAdminOAuthConnectionRoutes(app);
  registerAdminCacheRoutes(app);
  registerAdminConfigRoutes(app);
  registerAdminAppsRoutes(app);
  registerAdminModelsRoutes(app);
  registerAdminProvidersRoutes(app);
  registerAdminPromptsRoutes(app);
  registerAdminSourcesRoutes(app);
  registerAdminGroupRoutes(app);
  registerAdminContentAccessRoutes(app);
  registerAdminTranslateRoute(app);
  registerAdminPagesRoutes(app);
  registerAdminUIRoutes(app);
  await registerBackupRoutes(app);
  registerAdminSchemasRoutes(app);
  registerAdminVersionRoutes(app);
  registerAdminToolsRoutes(app);
  registerAdminSkillsRoutes(app);
  registerAdminMarketplaceRoutes(app);
  registerAdminLoggingRoutes(app);
  registerAdminSSLRoutes(app);
  registerAdminCorsRoutes(app);
  registerAdminSsrfRoutes(app);
  registerAdminProxyRoutes(app);
  registerAdminFeaturesRoutes(app);
  registerAdminUsageRoutes(app);
  registerAdminUpdateRoutes(app);
  registerIntegrationTestRoutes(app);
  registerAdminOfficeIntegrationRoutes(app);
  registerAdminBrowserExtensionRoutes(app);
  registerAdminNextcloudEmbedRoutes(app);
  registerAdminMcpServersRoutes(app);
  registerAdminCredentialsRoutes(app);
  registerAdminAgentsRoutes(app);
  registerAdminAgentInboxesRoutes(app);
  registerAdminSearchRoutes(app);
  registerAdminAuditLogRoutes(app);
  registerAdminChangelogRoutes(app);
  registerAdminChangesRoutes(app);
  registerAdminOverviewRoutes(app);
}
