import registerAdminAuthRoutes from './admin/auth.js';
import registerAdminOAuthRoutes from './admin/oauthClients.js';
import registerAdminCacheRoutes from './admin/cache.js';
import registerAdminConfigRoutes from './admin/configs.js';
import registerAdminAppsRoutes from './admin/apps.js';
import registerAdminModelsRoutes from './admin/models.js';
import registerAdminProvidersRoutes from './admin/providers.js';
import registerAdminPromptsRoutes from './admin/prompts.js';
import registerAdminSourcesRoutes from './admin/sources.js';
import registerAdminGroupRoutes from './admin/groups.js';
import registerAdminTranslateRoute from './admin/translate.js';
import registerAdminPagesRoutes from './admin/pages.js';
import registerAdminUIRoutes from './admin/ui.js';
import registerBackupRoutes from './admin/backup.js';
import registerAdminSchemasRoutes from './admin/schemas.js';
import registerAdminVersionRoutes from './admin/version.js';
import registerAdminToolsRoutes from './admin/tools.js';
import registerAdminLoggingRoutes from './admin/logging.js';
import registerAdminSSLRoutes from './admin/ssl.js';

export default async function registerAdminRoutes(app, basePath = '') {
  registerAdminAuthRoutes(app, basePath);
  registerAdminOAuthRoutes(app, basePath);
  registerAdminCacheRoutes(app, basePath);
  registerAdminConfigRoutes(app, basePath);
  registerAdminAppsRoutes(app, basePath);
  registerAdminModelsRoutes(app, basePath);
  registerAdminProvidersRoutes(app, basePath);
  registerAdminPromptsRoutes(app, basePath);
  registerAdminSourcesRoutes(app, basePath);
  registerAdminGroupRoutes(app, basePath);
  registerAdminTranslateRoute(app, basePath);
  registerAdminPagesRoutes(app, basePath);
  registerAdminUIRoutes(app, basePath);
  await registerBackupRoutes(app, basePath);
  registerAdminSchemasRoutes(app, basePath);
  registerAdminVersionRoutes(app, basePath);
  registerAdminToolsRoutes(app, basePath);
  registerAdminLoggingRoutes(app, basePath);
  registerAdminSSLRoutes(app, basePath);
}
