import registerAdminAuthRoutes from './admin/auth.js';
import registerAdminOAuthRoutes from './admin/oauthClients.js';
import registerAdminCacheRoutes from './admin/cache.js';
import registerAdminConfigRoutes from './admin/configs.js';
import registerAdminAppsRoutes from './admin/apps.js';
import registerAdminModelsRoutes from './admin/models.js';
import registerAdminProvidersRoutes from './admin/providers.js';
import registerAdminPromptsRoutes from './admin/prompts.js';
import registerAdminSourcesRoutes from './admin/sources.js';
import registerAdminGroupRoutes from './admin/groups.js';
import registerAdminTranslateRoute from './admin/translate.js';
import registerAdminPagesRoutes from './admin/pages.js';
import registerAdminUIRoutes from './admin/ui.js';
import registerBackupRoutes from './admin/backup.js';
import registerAdminSchemasRoutes from './admin/schemas.js';
import registerAdminVersionRoutes from './admin/version.js';
import registerAdminToolsRoutes from './admin/tools.js';
import registerAdminSkillsRoutes from './admin/skills.js';
import registerAdminMarketplaceRoutes from './admin/marketplace.js';
import registerAdminLoggingRoutes from './admin/logging.js';
import registerAdminSSLRoutes from './admin/ssl.js';
import registerAdminFeaturesRoutes from './admin/features.js';

export default async function registerAdminRoutes(app) {
  registerAdminAuthRoutes(app);
  registerAdminOAuthRoutes(app);
  registerAdminCacheRoutes(app);
  registerAdminConfigRoutes(app);
  registerAdminAppsRoutes(app);
  registerAdminModelsRoutes(app);
  registerAdminProvidersRoutes(app);
  registerAdminPromptsRoutes(app);
  registerAdminSourcesRoutes(app);
  registerAdminGroupRoutes(app);
  registerAdminTranslateRoute(app);
  registerAdminPagesRoutes(app);
  registerAdminUIRoutes(app);
  await registerBackupRoutes(app);
  registerAdminSchemasRoutes(app);
  registerAdminVersionRoutes(app);
  registerAdminToolsRoutes(app);
  registerAdminSkillsRoutes(app);
  registerAdminMarketplaceRoutes(app);
  registerAdminLoggingRoutes(app);
  registerAdminSSLRoutes(app);
  registerAdminFeaturesRoutes(app);
}
