# docker-compose.yml - Development Environment
version: '3.8'

services:
  # Main iHub Apps Development Container
  ihub-dev:
    build:
      context: ..
      target: development
      dockerfile: docker/Dockerfile
    container_name: ihub-dev
    ports:
      - '3000:3000' # Server port
      - '5173:5173' # Vite dev server port
    volumes:
      # Source code volumes for hot reload (read-only to prevent accidental changes)
      - ../server:/app/server:ro
      - ../client/src:/app/client/src:ro
      - ../shared:/app/shared:ro

      # Complete contents folder (bind mount for easy editing) - ALWAYS uses local folder
      - ../contents:/app/contents:rw

      # Override specific subdirectories with persistent volumes (mounted later = higher priority)
      - ihub-dev-data:/app/contents/data
      - ihub-dev-uploads:/app/contents/uploads
      - ihub-dev-logs:/app/logs

      # Node modules cache (performance optimization)
      - ihub-dev-node-modules:/app/node_modules
      - ihub-dev-client-modules:/app/client/node_modules
      - ihub-dev-server-modules:/app/server/node_modules
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=debug
      - WORKERS=1
      - PORT=3000
      - HOST=0.0.0.0
      - CORS_ORIGIN=http://localhost:5173
      - DEBUG_MODE=true
      - HOT_RELOAD=true
    env_file:
      - ../.env
    restart: unless-stopped
    networks:
      - ihub-network
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/api/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  # Development persistent volumes
  ihub-dev-data:
    driver: local
  ihub-dev-uploads:
    driver: local
  ihub-dev-logs:
    driver: local

  # Node modules caches for faster rebuilds
  ihub-dev-node-modules:
    driver: local
  ihub-dev-client-modules:
    driver: local
  ihub-dev-server-modules:
    driver: local

networks:
  ihub-network:
    driver: bridge
    name: ihub-network
