/**
 * Visible AI label on content that agents and workflows send to people
 * (Art. 50(1); guidelines ¶36: "an email generated by an AI agent … features
 * an AI label at the top"). Used for Jira comments written by the Jira tool,
 * the workflow HTTP node and shared chats; the Outlook add-in adds the same
 * label client-side.
 *
 * @module services/provenance/outboundLabel
 */
import configCache from '../../configCache.js';
import { getAiTransparencyConfig, isAiTransparencyActive } from './config.js';
import { getInstallationUrl } from './installation.js';

export const OUTBOUND_LABEL_TEXT = {
  en: 'AI-generated with iHub Apps',
  de: 'KI-generiert mit iHub Apps'
};

/** Whether outbound labels are on. */
export function outboundLabelEnabled() {
  return isAiTransparencyActive() && getAiTransparencyConfig().labels.outbound;
}

/**
 * The label line, in `language` or else the platform's default language
 * (outbound content has no viewer whose language we know).
 * @param {string} [language] - e.g. `de` or `de-DE`
 */
export function outboundLabel(language) {
  const lang = String(language || configCache.getPlatform()?.defaultLanguage || 'en')
    .toLowerCase()
    .split('-')[0];
  return OUTBOUND_LABEL_TEXT[lang] || OUTBOUND_LABEL_TEXT.en;
}

/**
 * Prefix plain text with the label (idempotent).
 * @param {string} text
 * @param {{language?: string}} [opts]
 */
export function labelPlainText(text, { language } = {}) {
  if (!outboundLabelEnabled() || typeof text !== 'string') return text;
  const label = `[${outboundLabel(language)}]`;
  if (text.startsWith(label)) return text;
  return `${label}\n\n${text}`;
}

/** HTTP headers marking a request body as AI-generated. */
export function outboundHeaders() {
  if (!outboundLabelEnabled()) return {};
  const url = getInstallationUrl();
  return {
    'X-AI-Generated': 'true',
    ...(url ? { 'X-AI-Provenance': `${url}/.well-known/ai-provenance` } : {})
  };
}
