import { useTranslation } from 'react-i18next';
import { Link } from 'react-router-dom';
import Icon from '../../../shared/components/Icon';

/**
 * Component to display the source of an AI answer (LLM, websearch, sources, workflow, ...).
 * Shows a non-intrusive badge indicating where the information came from.
 *
 * @param {Object} props
 * @param {Object} [props.answerSource] - LLM-side answer source metadata (sources array)
 * @param {Object} [props.workflowResult] - Workflow result metadata when message was produced by a workflow run
 *                                          ({ status, executionId, workflowName })
 */
function AnswerSourceBadge({ answerSource, workflowResult }) {
  const { t } = useTranslation();

  // Workflow output takes precedence over other sources: the message was produced
  // by a workflow run, not by the LLM responding from its own knowledge.
  if (workflowResult) {
    const displayName =
      typeof workflowResult.workflowName === 'object'
        ? workflowResult.workflowName.en || Object.values(workflowResult.workflowName)[0]
        : workflowResult.workflowName;
    const label = t('chatMessage.answerSource.workflow', 'Generated by workflow') +
      (displayName ? `: ${displayName}` : '');
    const colorClasses =
      'bg-cyan-100 text-cyan-700 dark:bg-cyan-900/30 dark:text-cyan-300 border-cyan-200 dark:border-cyan-800';

    if (workflowResult.executionId) {
      return (
        <Link
          to={`/workflows/executions/${workflowResult.executionId}`}
          className={`inline-flex items-center gap-1.5 px-2 py-0.5 rounded-full text-xs border hover:underline ${colorClasses}`}
          title={t(
            'chatMessage.answerSource.workflowTooltip',
            'Open workflow execution details'
          )}
        >
          <Icon name="cog" className="w-3 h-3" />
          <span>{label}</span>
          <Icon name="external-link" className="w-3 h-3" />
        </Link>
      );
    }

    return (
      <div
        className={`inline-flex items-center gap-1.5 px-2 py-0.5 rounded-full text-xs border ${colorClasses}`}
        title={label}
      >
        <Icon name="cog" className="w-3 h-3" />
        <span>{label}</span>
      </div>
    );
  }

  if (!answerSource || !answerSource.sources) {
    // No external sources used - show LLM-only badge
    return (
      <div
        className="inline-flex items-center gap-1.5 px-2 py-0.5 rounded-full text-xs bg-gray-100 text-gray-600 dark:bg-gray-800/50 dark:text-gray-400 border border-gray-200 dark:border-gray-700"
        title={t('chatMessage.answerSource.llmOnly')}
      >
        <Icon name="sparkles" className="w-3 h-3" />
        <span>{t('chatMessage.answerSource.llmOnly')}</span>
      </div>
    );
  }

  const { sources } = answerSource;

  // Determine the primary source to display
  let displayText = t('chatMessage.answerSource.mixed');
  let iconName = 'document-text';
  let colorClasses =
    'bg-blue-100 text-blue-700 dark:bg-blue-900/30 dark:text-blue-300 border-blue-200 dark:border-blue-800';

  if (sources.length === 1) {
    const source = sources[0];
    switch (source) {
      case 'websearch':
        displayText = t('chatMessage.answerSource.websearch');
        iconName = 'globe-alt';
        colorClasses =
          'bg-green-100 text-green-700 dark:bg-green-900/30 dark:text-green-300 border-green-200 dark:border-green-800';
        break;
      case 'sources':
        displayText = t('chatMessage.answerSource.sources');
        iconName = 'document-text';
        colorClasses =
          'bg-purple-100 text-purple-700 dark:bg-purple-900/30 dark:text-purple-300 border-purple-200 dark:border-purple-800';
        break;
      case 'iassistant':
        displayText = t('chatMessage.answerSource.iassistant');
        iconName = 'book-open';
        colorClasses =
          'bg-indigo-100 text-indigo-700 dark:bg-indigo-900/30 dark:text-indigo-300 border-indigo-200 dark:border-indigo-800';
        break;
      case 'grounding':
        displayText = t('chatMessage.answerSource.grounding');
        iconName = 'search';
        colorClasses =
          'bg-teal-100 text-teal-700 dark:bg-teal-900/30 dark:text-teal-300 border-teal-200 dark:border-teal-800';
        break;
      default:
        // Keep default mixed styling
        break;
    }
  } else if (sources.length > 1) {
    // Multiple sources - show mixed with tooltip listing all sources
    displayText = t('chatMessage.answerSource.mixed');
  }

  // Create tooltip text listing all sources
  const tooltipText =
    sources.length > 1
      ? `${t('chatMessage.answerSource.tooltip')}\n${sources.map(s => `• ${t(`chatMessage.answerSource.${s}`, s)}`).join('\n')}`
      : displayText;

  return (
    <div
      className={`inline-flex items-center gap-1.5 px-2 py-0.5 rounded-full text-xs border ${colorClasses}`}
      title={tooltipText}
    >
      <Icon name={iconName} className="w-3 h-3" />
      <span>{displayText}</span>
    </div>
  );
}

export default AnswerSourceBadge;
