apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: ai-hub-apps

# Common labels applied to all resources
commonLabels:
  app.kubernetes.io/name: ai-hub-apps
  app.kubernetes.io/instance: ai-hub-apps
  app.kubernetes.io/version: '1.0.5'
  app.kubernetes.io/managed-by: kustomize

# Resources to include
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - pvc.yaml
  - service.yaml
  - deployment.yaml
  - ingress.yaml
  - hpa.yaml

# Image configurations
images:
  - name: ghcr.io/intrafind/ai-hub-apps
    newTag: latest

# ConfigMap generators (optional - can be used instead of static configmaps)
# configMapGenerator:
# - name: ai-hub-apps-env
#   literals:
#   - NODE_ENV=production
#   - PORT=3000

# Secret generators (use with caution - secrets should be managed externally)
# secretGenerator:
# - name: ai-hub-apps-secrets
#   literals:
#   - OPENAI_API_KEY=placeholder

# Patches for different environments
patchesStrategicMerge:
# - deployment-patches.yaml

# JSON patches (6902)
# patchesJson6902:
# - target:
#     version: v1
#     kind: Deployment
#     name: ai-hub-apps
#   path: deployment-patch.yaml

# Replacements
# replacements:
# - source:
#     kind: ConfigMap
#     name: ai-hub-apps-config
#     fieldPath: data.PORT
#   targets:
#   - select:
#       kind: Service
#       name: ai-hub-apps
#     fieldPaths:
#     - spec.ports.[name=http].port
