apiVersion: v1
kind: Service
metadata:
  name: ai-hub-apps
  namespace: ai-hub-apps
  labels:
    app.kubernetes.io/name: ai-hub-apps
    app.kubernetes.io/component: service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: ai-hub-apps

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ai-hub-apps
  namespace: ai-hub-apps
  labels:
    app.kubernetes.io/name: ai-hub-apps
    app.kubernetes.io/component: serviceaccount
automountServiceAccountToken: false
