name: Build and Release Binaries

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag to attach binaries to (e.g., v1.0.0)'
        required: true
        default: ''
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # Quick build check job - runs on every push and pull request
  build-check:
    name: Build Check
    runs-on: ubuntu-latest
    # Only run on push or pull_request events
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci
          cd client && npm ci && cd ..
          cd server && npm ci && cd ..

      - name: Build client
        run: |
          cd client
          npm run build
          cd ..

      - name: Verify build
        run: |
          # Create production build
          npm run prod:build
          
          # Verify the build was successful
          if [ -d "dist" ] && [ -d "dist/public" ] && [ -d "dist/server" ]; then
            echo "✅ Build successful!"
          else
            echo "❌ Build failed! Missing expected output directories."
            exit 1
          fi
        shell: bash

  # Full build job - runs for releases and manual dispatch
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    # Only run on release or workflow_dispatch events
    if: github.event_name == 'release' || github.event_name == 'workflow_dispatch'
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            platform: linux
            binary_name: ai-hub-apps-linux
            pkg_target: node16-linux-x64
          - os: macos-latest
            platform: macos
            binary_name: ai-hub-apps-macos
            pkg_target: node16-macos-x64
          - os: windows-latest
            platform: win
            binary_name: ai-hub-apps-win.exe
            pkg_target: node16-win-x64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci
          cd client && npm ci && cd ..
          cd server && npm ci && cd ..

      - name: Build client
        run: |
          cd client
          npm run build
          cd ..

      - name: Prepare build directories
        run: |
          mkdir -p dist/public dist/server dist/config
          cp -r client/dist/* dist/public/
          cp -r server/*.js dist/server/
          cp server/*.cjs dist/server/
          cp -r server/adapters dist/server/
          cp server/package.json dist/server/
          cp -r config/* dist/config/
          cp package.json dist/
        shell: bash

      - name: Install production dependencies
        run: |
          cd dist
          npm install --production
          cd server
          npm install --production
          cd ../..
        shell: bash

      - name: Build binary
        run: |
          mkdir -p dist-bin
          npx pkg . --target ${{ matrix.pkg_target }} --output dist-bin/${{ matrix.binary_name }} --options max_old_space_size=4096
        shell: bash

      - name: Copy assets for binary
        run: |
          mkdir -p dist-bin/public dist-bin/config
          cp -r dist/public/* dist-bin/public/
          cp -r dist/config/* dist-bin/config/
          cp config.env dist-bin/
        shell: bash

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.binary_name }}
          path: dist-bin/${{ matrix.binary_name }}

      - name: Create platform-specific archive
        run: |
          cd dist-bin
          if [ "${{ matrix.os }}" == "windows-latest" ]; then
            7z a -tzip ../${{ matrix.binary_name }}.zip .
          else
            tar -czf ../${{ matrix.binary_name }}.tar.gz .
          fi
          cd ..
        shell: bash

      - name: Upload archive artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.binary_name }}-archive
          path: |
            ${{ matrix.binary_name }}.tar.gz
            ${{ matrix.binary_name }}.zip

  release:
    name: Attach to Release
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'release' || github.event_name == 'workflow_dispatch'
    permissions:
      contents: write
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Display structure of downloaded files
        run: ls -R ./artifacts
        shell: bash

      - name: Upload assets to release
        uses: softprops/action-gh-release@v2
        if: github.event_name == 'release'
        with:
          files: |
            ./artifacts/ai-hub-apps-linux/ai-hub-apps-linux
            ./artifacts/ai-hub-apps-linux-archive/ai-hub-apps-linux.tar.gz
            ./artifacts/ai-hub-apps-macos/ai-hub-apps-macos
            ./artifacts/ai-hub-apps-macos-archive/ai-hub-apps-macos.tar.gz
            ./artifacts/ai-hub-apps-win.exe/ai-hub-apps-win.exe
            ./artifacts/ai-hub-apps-win.exe-archive/ai-hub-apps-win.exe.zip

      # Manual workflow dispatch asset uploads
      - name: Upload assets for manual workflow
        if: github.event_name == 'workflow_dispatch'
        run: |
          # Linux binary
          gh release upload ${{ github.event.inputs.release_tag }} ./artifacts/ai-hub-apps-linux/ai-hub-apps-linux --clobber
          
          # Linux archive
          gh release upload ${{ github.event.inputs.release_tag }} ./artifacts/ai-hub-apps-linux-archive/ai-hub-apps-linux.tar.gz --clobber
          
          # macOS binary
          gh release upload ${{ github.event.inputs.release_tag }} ./artifacts/ai-hub-apps-macos/ai-hub-apps-macos --clobber
          
          # macOS archive
          gh release upload ${{ github.event.inputs.release_tag }} ./artifacts/ai-hub-apps-macos-archive/ai-hub-apps-macos.tar.gz --clobber
          
          # Windows binary
          gh release upload ${{ github.event.inputs.release_tag }} ./artifacts/ai-hub-apps-win.exe/ai-hub-apps-win.exe --clobber
          
          # Windows archive
          gh release upload ${{ github.event.inputs.release_tag }} ./artifacts/ai-hub-apps-win.exe-archive/ai-hub-apps-win.exe.zip --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}