name: Build and Release Binaries

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag to attach binaries to (e.g., v1.0.0)'
        required: true
        default: ''
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # Quick build check job - runs on every push and pull request
  build-check:
    name: Build Check
    runs-on: ubuntu-latest
    # Only run on push or pull_request events
    if: github.event_name == 'push' || github.event_name == 'pull_request'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: 'latest'

      - name: Install dependencies
        run: |
          npm ci
          cd client && npm ci && cd ..
          cd server && npm ci && cd ..

      - name: Install client dependencies with uuid package
        run: |
          cd client
          npm install
          npm install uuid
          cd ..

      - name: Build client
        run: |
          cd client
          npm run build
          cd ..

      - name: Verify build
        run: |
          # Create production build
          npm run prod:build

          # Verify the build was successful
          if [ -d "dist" ] && [ -d "dist/public" ] && [ -d "dist/server" ]; then
            echo "✅ Build successful!"
          else
            echo "❌ Build failed! Missing expected output directories."
            exit 1
          fi
        shell: bash

  # Full build job - runs for releases and manual dispatch
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    # Only run on release or workflow_dispatch events
    if: github.event_name == 'release' || github.event_name == 'workflow_dispatch'
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            platform: linux
            binary_extension: ''
          - os: macos-latest
            platform: macos
            binary_extension: ''
          - os: windows-latest
            platform: win
            binary_extension: '.exe'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: 'latest'

      - name: Install dependencies
        run: |
          npm ci
          cd client && npm ci && npm install uuid && cd ..
          cd server && npm ci && cd ..

      - name: Set version
        run: |
          if [ "${{ github.event_name }}" == "release" ]; then
            echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          else
            echo "VERSION=${{ github.event.inputs.release_tag }}" >> $GITHUB_ENV
          fi
          # Set versioned name for binary
          echo "VERSIONED_NAME=ihub-apps-${{ env.VERSION }}-${{ matrix.platform }}${{ matrix.binary_extension }}" >> $GITHUB_ENV
        shell: bash

      - name: Sync package.json version with release tag
        run: |
          if [ -n "${{ env.VERSION }}" ]; then
            echo "Syncing version with release tag: ${{ env.VERSION }}"
            node scripts/sync-release-version.js ${{ env.VERSION }}
          fi
        shell: bash

      - name: Build using Node.js SEA
        run: |
          # Use Node.js SEA (Single Executable Application) feature with platform-specific argument
          chmod +x ./build-sea.sh
          ./build-sea.sh ${{ matrix.platform }}
        shell: bash

      - name: Windows-specific setup
        if: matrix.platform == 'win'
        run: |
          # Check Windows binary architecture
          node -e "console.log('Windows build: Node.js architecture is ' + process.arch)"

          # Create a simple diagnostic script for Windows
          echo '@echo off
          echo Windows Diagnostic Information:
          echo -----------------------------
          echo Node Version: %NODE_VERSION%
          echo Architecture: %PROCESSOR_ARCHITECTURE%
          echo Processor: %PROCESSOR_IDENTIFIER%
          echo System Type: %PROCESSOR_ARCHITECTURE%
          echo Number of Processors: %NUMBER_OF_PROCESSORS%
          pause
          ' > dist-bin/windows-check.bat

          chmod +x dist-bin/windows-check.bat
        shell: bash

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: binary-${{ matrix.platform }}-${{ env.VERSION }}
          path: |
            dist-bin/ihub-apps-v*-${{ matrix.platform }}${{ matrix.binary_extension }}
            dist-bin/ihub-apps-v*-win.bat
            dist-bin/ihub-apps-v*-${{ matrix.platform }}

      - name: Create platform-specific archive
        run: |
          cd dist-bin
          # Create versioned archive name
          if [ "${{ matrix.os }}" == "windows-latest" ]; then
            VERSIONED_ARCHIVE_NAME="ihub-apps-${{ env.VERSION }}-win"
            7z a -tzip ../$VERSIONED_ARCHIVE_NAME.zip .
          else
            VERSIONED_ARCHIVE_NAME="ihub-apps-${{ env.VERSION }}-${{ matrix.platform }}"
            tar -czf ../$VERSIONED_ARCHIVE_NAME.tar.gz .
          fi
          echo "VERSIONED_ARCHIVE_NAME=$VERSIONED_ARCHIVE_NAME" >> $GITHUB_ENV
          cd ..
        shell: bash

      - name: Create base64 encoded archives
        run: |
          # Create base64 encoded versions for customers who cannot download zip files
          # These text files contain the entire binary archive encoded as base64
          # Customers can download the .txt file and decode it to get the original archive
          if [ "${{ matrix.os }}" == "windows-latest" ]; then
            ARCHIVE_FILE="${{ env.VERSIONED_ARCHIVE_NAME }}.zip"
            BASE64_FILE="${{ env.VERSIONED_ARCHIVE_NAME }}.zip.base64.txt"
          else
            ARCHIVE_FILE="${{ env.VERSIONED_ARCHIVE_NAME }}.tar.gz"
            BASE64_FILE="${{ env.VERSIONED_ARCHIVE_NAME }}.tar.gz.base64.txt"
          fi
          
          # Generate base64 encoded version
          echo "Creating base64 encoded version of $ARCHIVE_FILE..."
          # Use platform-specific base64 command syntax
          if [ "${{ matrix.os }}" == "macos-latest" ]; then
            # macOS requires -i flag for input file
            base64 -i "$ARCHIVE_FILE" -o "$BASE64_FILE"
          else
            # Linux and Windows (Git Bash) use standard syntax
            base64 "$ARCHIVE_FILE" > "$BASE64_FILE"
          fi
          
          # Verify the base64 file was created and has content
          if [ -f "$BASE64_FILE" ] && [ -s "$BASE64_FILE" ]; then
            echo "✅ Successfully created base64 encoded file: $BASE64_FILE"
            echo "File size: $(wc -c < "$BASE64_FILE") bytes"
            echo "First 100 characters:"
            head -c 100 "$BASE64_FILE"
            echo ""
          else
            echo "❌ Failed to create base64 encoded file"
            exit 1
          fi
          
          # Set environment variable for the base64 file name
          echo "BASE64_FILE=$BASE64_FILE" >> $GITHUB_ENV
        shell: bash

      - name: Upload archive artifact
        uses: actions/upload-artifact@v4
        with:
          name: archive-${{ matrix.platform }}-${{ env.VERSION }}
          path: |
            ${{ env.VERSIONED_ARCHIVE_NAME }}.tar.gz
            ${{ env.VERSIONED_ARCHIVE_NAME }}.zip
            ${{ env.BASE64_FILE }}

  # Commit version changes back to repository
  commit-version:
    name: Commit Version Changes
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'release' || github.event_name == 'workflow_dispatch'
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Set version for commit job
        run: |
          if [ "${{ github.event_name }}" == "release" ]; then
            echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          else
            echo "VERSION=${{ github.event.inputs.release_tag }}" >> $GITHUB_ENV
          fi
        shell: bash

      - name: Sync and commit version changes
        run: |
          echo "Syncing and committing version changes for ${{ env.VERSION }}"
          node scripts/sync-release-version.js ${{ env.VERSION }} --commit
          
          # Push changes back to the repository
          git push origin HEAD:${{ github.ref_name }} || echo "No changes to push or push failed"
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    name: Attach to Release
    needs: [build, commit-version]
    runs-on: ubuntu-latest
    if: github.event_name == 'release' || github.event_name == 'workflow_dispatch'
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set version for release job
        run: |
          if [ "${{ github.event_name }}" == "release" ]; then
            echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          else
            echo "VERSION=${{ github.event.inputs.release_tag }}" >> $GITHUB_ENV
          fi
        shell: bash

      - name: Setup GitHub CLI
        run: |
          echo "Using GitHub CLI that's pre-installed on the runner..."
          # Verify gh is installed and authenticated through GITHUB_TOKEN
          gh --version
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Add decode helper script to release
        run: |
          # Copy the decode script to artifacts so it's included in the release
          cp scripts/decode-base64-binary.sh ./artifacts/
          echo "✅ Added decode-base64-binary.sh to release artifacts"
        shell: bash

      - name: Display structure of downloaded files
        run: ls -R ./artifacts
        shell: bash

      - name: Upload assets to release
        uses: softprops/action-gh-release@v2
        if: github.event_name == 'release' || github.event_name == 'workflow_dispatch'
        with:
          files: ./artifacts/**/*.*
          tag_name: ${{ env.VERSION }}
          # Don't create a new release, just upload files to existing one
          draft: false
          prerelease: false
          # This will update the existing release instead of creating a new one
          overwrite: true
