/**
 * Fixture builders for the document extraction tests.
 *
 * Builds minimal but structurally honest Office packages from raw XML so tests
 * control every part that matters (styles.xml, numbering.xml, headers, ...) and
 * need no opaque binary fixtures. The ArrayBuffer is generated by JSZip inside
 * the test realm: mammoth's browser build rejects a Node Buffer's ArrayBuffer
 * (cross-realm), and jsdom's File may lack arrayBuffer().
 */
import JSZip from 'jszip';

export const DOCX_MIME = 'application/vnd.openxmlformats-officedocument.wordprocessingml.document';

const TRANSITIONAL = {
  w: 'http://schemas.openxmlformats.org/wordprocessingml/2006/main',
  r: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships',
  rel: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships'
};
const STRICT = {
  w: 'http://purl.oclc.org/ooxml/wordprocessingml/main', // NOSONAR
  r: 'http://purl.oclc.org/ooxml/officeDocument/relationships', // NOSONAR
  rel: 'http://purl.oclc.org/ooxml/officeDocument/relationships' // NOSONAR
};

/** jsdom's File may lack arrayBuffer(); the extractors only need name/type/arrayBuffer. */
export function makeFile(arrayBuffer, name, type) {
  const file = new File([arrayBuffer], name, { type });
  if (typeof file.arrayBuffer !== 'function') file.arrayBuffer = async () => arrayBuffer;
  return file;
}

/** One paragraph; `ppr` / `rpr` are raw inner XML of w:pPr / w:rPr. */
export const p = (text, ppr = '', rpr = '') =>
  `<w:p>${ppr ? `<w:pPr>${ppr}</w:pPr>` : ''}<w:r>${rpr ? `<w:rPr>${rpr}</w:rPr>` : ''}` +
  `<w:t xml:space="preserve">${text}</w:t></w:r></w:p>`;

/** A numbering level definition for numbering.xml. */
export const lvl = (ilvl, numFmt, lvlText, start = 1) =>
  `<w:lvl w:ilvl="${ilvl}"><w:start w:val="${start}"/><w:numFmt w:val="${numFmt}"/>` +
  `<w:lvlText w:val="${lvlText}"/></w:lvl>`;

export const numPr = (numId, ilvl = 0) =>
  `<w:numPr><w:ilvl w:val="${ilvl}"/><w:numId w:val="${numId}"/></w:numPr>`;

/**
 * Minimal DOCX from raw WordprocessingML: `body` (w:body content), `styles`
 * (w:style elements), `numbering` (w:abstractNum / w:num), optional extra parts
 * such as { 'word/header1.xml': '…' } plus `rels` entries for them.
 * Pass `styles: null` / `numbering: null` to leave the part out of the package.
 * `contentTypes` adds raw <Default>/<Override> entries, `binaryParts` maps a part path to
 * base64 content, `strict` builds a Strict OOXML package (other namespaces).
 * Returns a File whose arrayBuffer was produced in the test realm.
 */
export async function buildDocxFile(
  {
    body,
    styles = '',
    numbering = '',
    parts = {},
    binaryParts = {},
    rels = '',
    contentTypes = '',
    strict = false
  },
  name = 'test.docx'
) {
  const ns = strict ? STRICT : TRANSITIONAL;
  const W_NS = `xmlns:w="${ns.w}" xmlns:r="${ns.r}"`;
  const zip = new JSZip();
  const hasStyles = typeof styles === 'string';
  const hasNumbering = typeof numbering === 'string';
  zip.file(
    '[Content_Types].xml',
    '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">' +
      '<Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>' +
      '<Default Extension="xml" ContentType="application/xml"/>' +
      '<Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>' +
      (hasStyles
        ? '<Override PartName="/word/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml"/>'
        : '') +
      (hasNumbering
        ? '<Override PartName="/word/numbering.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.numbering+xml"/>'
        : '') +
      `${contentTypes}</Types>`
  );
  zip.file(
    '_rels/.rels',
    '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">' +
      `<Relationship Id="rId1" Type="${ns.rel}/officeDocument" Target="word/document.xml"/></Relationships>`
  );
  zip.file(
    'word/_rels/document.xml.rels',
    '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">' +
      (hasStyles ? `<Relationship Id="rIdS" Type="${ns.rel}/styles" Target="styles.xml"/>` : '') +
      (hasNumbering
        ? `<Relationship Id="rIdN" Type="${ns.rel}/numbering" Target="numbering.xml"/>`
        : '') +
      `${rels}</Relationships>`
  );
  if (hasStyles) {
    zip.file(
      'word/styles.xml',
      `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:styles ${W_NS}>${styles}</w:styles>`
    );
  }
  if (hasNumbering) {
    zip.file(
      'word/numbering.xml',
      `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:numbering ${W_NS}>${numbering}</w:numbering>`
    );
  }
  zip.file(
    'word/document.xml',
    `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:document ${W_NS}><w:body>${body}</w:body></w:document>`
  );
  for (const [path, xml] of Object.entries(parts)) zip.file(path, xml);
  for (const [path, base64] of Object.entries(binaryParts))
    zip.file(path, base64, { base64: true });
  const arrayBuffer = await zip.generateAsync({ type: 'arraybuffer' });
  return makeFile(arrayBuffer, name, DOCX_MIME);
}

/** Content type + relationship entries for an optional part, to pass as `contentTypes` / `rels`. */
export const partOverride = (partName, contentType) =>
  `<Override PartName="${partName}" ContentType="${contentType}"/>`;
export const relationship = (id, type, target, external = false) =>
  `<Relationship Id="${id}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/${type}" Target="${target}"${external ? ' TargetMode="External"' : ''}/>`;

/** A table; `rows` are arrays of raw <w:tc> XML. */
export const tbl = (...rows) =>
  `<w:tbl><w:tblPr/><w:tblGrid/>${rows.map(cells => `<w:tr>${cells.join('')}</w:tr>`).join('')}</w:tbl>`;
/** A table cell; `props` is raw inner XML of w:tcPr. A cell must end with a paragraph. */
export const tc = (content, props = '') =>
  `<w:tc>${props ? `<w:tcPr>${props}</w:tcPr>` : ''}${content}</w:tc>`;

/**
 * German Word heading styles (style IDs `berschrift1`, names `heading 1`) bound to a
 * multilevel list (numId 1), plus a corporate heading style with only an outline level.
 */
export const HEADING_STYLES = `
  <w:style w:type="paragraph" w:styleId="berschrift1"><w:name w:val="heading 1"/>
    <w:pPr><w:numPr><w:numId w:val="1"/></w:numPr><w:outlineLvl w:val="0"/></w:pPr></w:style>
  <w:style w:type="paragraph" w:styleId="berschrift2"><w:name w:val="heading 2"/><w:basedOn w:val="berschrift1"/>
    <w:pPr><w:numPr><w:ilvl w:val="1"/><w:numId w:val="1"/></w:numPr><w:outlineLvl w:val="1"/></w:pPr></w:style>
  <w:style w:type="paragraph" w:customStyle="1" w:styleId="IFKapitel"><w:name w:val="IF Kapitel"/>
    <w:pPr><w:outlineLvl w:val="0"/></w:pPr></w:style>`;

/** Heading numbering `1.` / `1.1` for HEADING_STYLES (abstractNum 0 → numId 1). */
export const HEADING_NUMBERING =
  `<w:abstractNum w:abstractNumId="0">${lvl(0, 'decimal', '%1.')}${lvl(1, 'decimal', '%1.%2')}</w:abstractNum>` +
  '<w:num w:numId="1"><w:abstractNumId w:val="0"/></w:num>';

// ---------------------------------------------------------------------------------------------
// OpenDocument

const ODF_NS = {
  office: 'urn:oasis:names:tc:opendocument:xmlns:office:1.0',
  style: 'urn:oasis:names:tc:opendocument:xmlns:style:1.0',
  text: 'urn:oasis:names:tc:opendocument:xmlns:text:1.0',
  table: 'urn:oasis:names:tc:opendocument:xmlns:table:1.0',
  draw: 'urn:oasis:names:tc:opendocument:xmlns:drawing:1.0',
  presentation: 'urn:oasis:names:tc:opendocument:xmlns:presentation:1.0',
  fo: 'urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0',
  svg: 'urn:oasis:names:tc:opendocument:xmlns:svg-compatible:1.0',
  xlink: 'http://www.w3.org/1999/xlink',
  xml: 'http://www.w3.org/XML/1998/namespace' // NOSONAR — a namespace name, never requested
};
const ODF_NS_DECL = Object.entries(ODF_NS)
  .filter(([prefix]) => prefix !== 'xml')
  .map(([prefix, uri]) => `xmlns:${prefix}="${uri}"`)
  .join(' ');

export const ODF_MIME = {
  text: 'application/vnd.oasis.opendocument.text',
  spreadsheet: 'application/vnd.oasis.opendocument.spreadsheet',
  presentation: 'application/vnd.oasis.opendocument.presentation'
};

/**
 * A minimal OpenDocument package from raw XML: `body` is the content of office:text /
 * office:spreadsheet / office:presentation, `automatic` the automatic styles of content.xml,
 * `styles` the office:styles of styles.xml (named styles, list styles), `outline` an optional
 * text:outline-style element for styles.xml. `type` is text, spreadsheet or presentation.
 */
export async function buildOdfFile(
  {
    type = 'text',
    body,
    automatic = '',
    styles = '',
    outline = '',
    masterStyles = '',
    noMimetype = false
  },
  name = `test.${{ text: 'odt', spreadsheet: 'ods', presentation: 'odp' }[type]}`
) {
  const zip = new JSZip();
  if (!noMimetype) zip.file('mimetype', ODF_MIME[type], { compression: 'STORE' });
  const xmlHead = '<?xml version="1.0" encoding="UTF-8"?>';
  zip.file(
    'META-INF/manifest.xml',
    `${xmlHead}<manifest:manifest xmlns:manifest="urn:oasis:names:tc:opendocument:xmlns:manifest:1.0" manifest:version="1.2"/>`
  );
  zip.file(
    'content.xml',
    `${xmlHead}<office:document-content ${ODF_NS_DECL} office:version="1.2">` +
      `<office:automatic-styles>${automatic}</office:automatic-styles>` +
      `<office:body><office:${type}>${body}</office:${type}></office:body></office:document-content>`
  );
  zip.file(
    'styles.xml',
    `${xmlHead}<office:document-styles ${ODF_NS_DECL} office:version="1.2">` +
      `<office:styles>${outline}${styles}</office:styles>${masterStyles}</office:document-styles>`
  );
  const arrayBuffer = await zip.generateAsync({ type: 'arraybuffer', mimeType: ODF_MIME[type] });
  return makeFile(arrayBuffer, name, ODF_MIME[type]);
}

/** ODF paragraph / heading / span helpers. */
export const odfP = (text, style = '') =>
  `<text:p${style ? ` text:style-name="${style}"` : ''}>${text}</text:p>`;
export const odfH = (text, level, style = '') =>
  `<text:h${style ? ` text:style-name="${style}"` : ''} text:outline-level="${level}">${text}</text:h>`;
